### ISSUE TITLE
the server keeps crashing

### ISSUE THREAD

**Issue by Hussein-miracle** [abetwothree/youtube-music-rest-api-microservice#1]
it keeps saying some of the functions you're  calling are not functions

**Comment by abetwothree** [comment]
It should work for most endpoints. The only endpoint that doesn't work out of the box is the individual song endpoint (`/song/:id`) because I submitted a PR for that to be implemented on the YouTube Music API repo but no progress has been had on it over there.

If other endpoints don't work I'd recommend checking your Node JS and NPM versions. I used Node 12 and NPM 6.14.

https://github.com/emresenyuva/youtube-music-api/pull/29
